[ironic] use static ironic-db-migration job name
Don't use random suffix for ironic db migration jobs, it prevents executed jobs from being deleted and might cause an
upgrade error like this:
```
Error: UPGRADE FAILED: pre-upgrade hooks failed: unable to build kubernetes object for deleting hook
ironic/templates/db-migration-job.yaml: resource mapping not found for name: "ironic-db-migration-dzyj" namespace: ""
from "": no matches for kind "Job" in version ""
ensure CRDs are installed first
```

We don't need to randomize it, as this job has a following hook configuration:
```
"helm.sh/hook": "post-install,pre-upgrade"
"helm.sh/hook-weight": "-1"
"helm.sh/hook-delete-policy": "before-hook-creation"
```